"""Subset Libertinus Serif (Regular + Italic) and embed it in css/fonts.css as data URIs,
so the samplebook renders in Libertinus even when index.html is opened straight from disk.

Run:   python tools/build_fonts.py
Needs: fonttools, brotli, and Libertinus Serif installed (or pass the folder holding the .ttf files).
"""
import base64
import io
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\Windows\Fonts")

UNICODES = (
    list(range(0x20, 0x7F))        # Basic Latin
    + list(range(0xA0, 0x250))     # Latin-1, Latin Extended-A/B
    + list(range(0x370, 0x400))    # Greek (µ, α, β … in recipes)
    + list(range(0x2000, 0x20A0))  # punctuation, super/subscripts (CO₂)
    + list(range(0x2100, 0x2200))  # letterlike (№, ℃)
    + list(range(0x2190, 0x2200))  # arrows
    + list(range(0x2200, 0x2300))  # maths (≈ ≤ ≥ ±)
    + [0x25B6]                     # ▶
)

FACES = [("Regular", "normal"), ("Italic", "italic")]


def woff2_b64(path):
    font = TTFont(path)
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = ["kern", "liga", "clig", "calt", "mark", "mkmk"]
    opts.name_IDs = ["*"]
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=UNICODES)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    return base64.b64encode(buf.getvalue()).decode("ascii"), len(buf.getvalue())


def main():
    rules = ["/* Generated by tools/build_fonts.py: Libertinus Serif (SIL Open Font License), subset + embedded. */"]
    for name, style in FACES:
        data, size = woff2_b64(os.path.join(SRC, f"LibertinusSerif-{name}.ttf"))
        print(f"{name}: {size // 1024} KB")
        rules.append(
            "@font-face {\n"
            '  font-family: "Libertinus Serif";\n'
            f'  src: local("Libertinus Serif{"" if name == "Regular" else " " + name}"),\n'
            f'       url(data:font/woff2;base64,{data}) format("woff2");\n'
            f"  font-weight: 400; font-style: {style}; font-display: block;\n"
            "}"
        )
    with open(os.path.join(PROJ, "css", "fonts.css"), "w", encoding="utf-8") as f:
        f.write("\n".join(rules) + "\n")


if __name__ == "__main__":
    main()
